# Generated by Django 4.2.3 on 2023-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.CharField(default=None, max_length=155),
            preserve_default=False,
        ),
    ]
