# Generated by Django 4.2.3 on 2023-07-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_products_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
