# Generated by Django 4.2.3 on 2023-07-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('working', 'Working on it'), ('done', 'Done')], max_length=20),
        ),
    ]
