# Generated by Django 4.2.3 on 2023-07-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('working', 'Working on it'), ('ready_to_pickup', 'Ready to pickup'), ('done', 'Done')], max_length=20),
        ),
    ]
