version: '3.8'

services:

  web:
    image: todordaskalov/bakeryproject
    environment:
      - TZ=Europe/Sofia
    build: .
    command: gunicorn --bind=0.0.0.0:8000 bakeryProject.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /tmp/bakeryProject/staticfiles:/app/staticfiles
  postgres:    
    image: postgres
    container_name: bakery_postgres_db
    restart: always
    environment:
      POSTGRES_DB: bakery_db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Sofia"
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    environment:
      - TZ=Europe/Sofia
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/bakeryProject/staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
