version: '3.8'

services:

  web:
    image: bakeryproject
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    env_file:
      - .env
  postgres:    
    image: postgres:latest
    container_name: bakery_postgres_db
    restart: always
    environment:
      POSTGRES_DB: bakery_db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
