version: '3.8'

services:

  web:
    image: todordaskalov/bakeryproject
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --insecure
    ports:
      - "8000:8000"
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: bakery_postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
