# Generated by Django 4.2.3 on 2023-07-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_newcartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCartItem',
        ),
    ]
