# Generated by Django 4.2.3 on 2023-07-08 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='bakeryuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='bakeryuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='bakeryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bakeryuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bakeryuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bakeryuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='bakeryuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='bakeryuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
