# Generated by Django 4.2.3 on 2023-07-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_main', '0003_bakeryuser_groups_bakeryuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryuser',
            name='profile',
        ),
        migrations.AddField(
            model_name='bakeryuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bakeryuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
