# Generated by Django 4.2.3 on 2023-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('salty', 'Salty'), ('sweet', 'Sweet'), ('coffees', 'Coffees')], default='salty', max_length=10),
            preserve_default=False,
        ),
    ]
