# Generated by Django 4.2.3 on 2023-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('salty', 'Salty'), ('sweet', 'Sweet'), ('drinks', 'Drinks')], max_length=10),
        ),
    ]
